---
name: Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  tests:
    name: "Python ${{ matrix.python }}"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        include:
        - name: py37
          python: 3.7
          tox: py37
        - name: py38
          python: 3.8
          tox: py38
        - name: py39
          python: 3.9
          coverage: true
          tox: py39
        - name: py310
          python: "3.10"
          tox: py310
        - name: py311
          python: "3.11"
          tox: py311

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v4"
        with:
          python-version: "${{ matrix.python }}"
      - name: "Install dependencies"
        run: |
          set -xe
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel

      - name: "Run tests"
        run: |
          pip install tox
          tox -e ${{ matrix.tox }}

      - name: "Run coverage"
        if: matrix.coverage
        run: |
          python -m pip install --upgrade codecov
          codecov
